### ISSUE TITLE
ChildIOException: File/directory is a child to another output

### ISSUE THREAD

**Issue by matthewangel** [CCBR/Pipeliner#469] opened 2021-11-02 13:05 UTC
Getting an ChildIOException error when performing a dry run on the rna-seq pipeline (initialqcrnaseq.snakefile).

ChildIOException: File/directory is a child to another output
/data/NCI_VB/pavlakis/georgetown/nazli_ascorbic_acid/pipeliner/logfiles
/data/NCI_VB/pavlakis/georgetown/nazli_ascorbic_acid/pipeliner/logfiles/IL2_Exp1.RnaSeqMetrics.txt

log_dir cannot be the output of the get_strandness rule (line 669) with children (any containing file) as outputs of other rules. I don't believe this variable is called by name in the rule and can probably be deleted, but the workflow runs correctly when it is moved to the params section.

**Comment by skchronicles** [comment] 2021-11-03 14:52
## Update

@matthewangel and I could not reproduce the error; however it is worth modifying the `rule get_strandness` to move the _outdir_ declaration in the _output_ section to the _params_ section. 

I will keep this issue open until I have time to make and test the change.

**Before**
```python
rule get_strandness:
  input: 
    groupsfile=join(workpath,"groups.tab"),
    files=expand(join(workpath,log_dir,"{name}.RnaSeqMetrics.txt"),name=samples),
  output: 
    outfile=join(workpath,log_dir,"strandness.txt"),
    outdir=join(workpath,log_dir)
  params: 
    rname='pl:get_strandness',
    pythonver=config['bin'][pfamily]['tool_versions']['PYTHONVER'],
    pythonscript=join(workpath,"Scripts","get_strandness.py")
  run:
    import os
    os.chdir(output.outdir)
    check_readaccess(input.groupsfile)
    os.system("module load "+params.pythonver+";python "+params.pythonscript+" "+input.groupsfile+" > "+output.outfile)
    strandfile=open(output.outfile,'r')
    strandness=strandfile.readline().strip()
    strandfile.close()
    A=open(join(workpath,"run.json"),'r')
    a=eval(A.read())
    A.close()
    config=dict(a.items())
    config['project']['STRANDED']=strandness
    with open(join(workpath,'run.json'),'w') as F:
      json.dump(config, F, sort_keys = True, indent = 4,ensure_ascii=False)
    F.close()
``` 

**After**
```python
rule get_strandness:
  input: 
    groupsfile=join(workpath,"groups.tab"),
    files=expand(join(workpath,log_dir,"{name}.RnaSeqMetrics.txt"),name=samples),
  output: 
    outfile=join(workpath,log_dir,"strandness.txt"),
  params: 
    rname='pl:get_strandness',
    pythonver=config['bin'][pfamily]['tool_versions']['PYTHONVER'],
    pythonscript=join(workpath,"Scripts","get_strandness.py"),
    outdir=join(workpath,log_dir)
  run:
    import os
    os.chdir(params.outdir)
    check_readaccess(input.groupsfile)
    os.system("module load "+params.pythonver+";python "+params.pythonscript+" "+input.groupsfile+" > "+output.outfile)
    strandfile=open(output.outfile,'r')
    strandness=strandfile.readline().strip()
    strandfile.close()
    A=open(join(workpath,"run.json"),'r')
    a=eval(A.read())
    A.close()
    config=dict(a.items())
    config['project']['STRANDED']=strandness
    with open(join(workpath,'run.json'),'w') as F:
      json.dump(config, F, sort_keys = True, indent = 4,ensure_ascii=False)
    F.close()
```

**Comment by epehrsson** [comment] 2021-11-29 21:42
Get a similar error when performing a dry run on the rna-seq pipeline:

Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
/data/LCP_Omics/pilot_project/external/zhao/initialQC/logfiles
/data/LCP_Omics/pilot_project/external/zhao/initialQC/logfiles/strandness.txt

**Comment by skchronicles** [comment] 2022-01-20 21:17
This issue has been fixed with https://github.com/CCBR/Pipeliner/commit/6df709cd6df709f96711cc1b6dc79bad01c16f69 on the activeDev branch.

**Closed by skchronicles** 2022-01-20 21:17 UTC
